### ISSUE TITLE
libGL error

### ISSUE THREAD

**Issue by natbutter** [tashrifbillah/glxgears-containers#1]
Hi there, I am trying to run glxgears via the docker container, host is xubuntu 20.04, and NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6.

I get the following dump of libGL errors (and no appearance of glxgears). 
```
user@machine:~$ xhost +
access control disabled, clients can connect from any host
user@machine:~$ sudo docker run --rm -ti -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY  --privileged tbillah/glxgears-docker
[root@61f9afe90a5c tmp]# glxgears
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  45
  Current serial number in output stream:  47
[root@61f9afe90a5c tmp]# 
```

Running `glxgears` on the host works fine. I have tried a few other images and GUI applications and they result in the same issue, so I think this is a host problem or some docker flag I need to pass, nevertheless any suggestions? Thanks

**Comment by tashrifbillah** [comment]
Hi @natbutter , does your Ubuntu host have i965_dri.so and swrast_dri.so ?

**Comment by tashrifbillah** [comment]
In other words, you can do `ldd glxgears` on the host to see what libraries it calls.

**Comment by natbutter** [comment]
Thanks for responding on a 4 year old repo! 
Okay, I went down a few library paths and may have added a few extra to my host (`sudo apt install libgl1-mesa-dri
mesa-utils libgl1-mesa-glx
`), but what I still needed *inside* the container was 
```
yum install mesa-dri-drivers
```
All working now! Thank you

**Comment by tashrifbillah** [comment]
No problem. I am glad that you solved the issue.

So I already have `mesa-dri-drivers` in my Singularity recipe:
https://github.com/tashrifbillah/glxgears-containers/blob/decf61d3cb1782e551b93506f44d55b93c028329/Singularity#L5

I wonder why I do not have that in my Docker recipe. It is probably because that library's function was already performed by [-v /tmp/.X11-unix:/tmp/.X11-unix](https://github.com/tashrifbillah/glxgears-containers#isolated-way)
